# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/qtz-robot/pyqt_test/client.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1104, 750)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(391, 271))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.video = QtWidgets.QLabel(self.tab)
        self.video.setStyleSheet("font: 75 28pt \"Umpush\";")
        self.video.setObjectName("video")
        self.gridLayout.addWidget(self.video, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout_5.addWidget(self.tabWidget, 3, 3, 3, 4)
        self.speed_accpect = QtWidgets.QCheckBox(self.centralwidget)
        self.speed_accpect.setObjectName("speed_accpect")
        self.gridLayout_5.addWidget(self.speed_accpect, 6, 2, 1, 1, QtCore.Qt.AlignRight)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.porttext = QtWidgets.QLineEdit(self.centralwidget)
        self.porttext.setObjectName("porttext")
        self.horizontalLayout_2.addWidget(self.porttext)
        self.disconnect = QtWidgets.QPushButton(self.centralwidget)
        self.disconnect.setStyleSheet("")
        self.disconnect.setObjectName("disconnect")
        self.horizontalLayout_2.addWidget(self.disconnect)
        self.gridLayout_5.addLayout(self.horizontalLayout_2, 10, 1, 1, 6)
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setObjectName("label_20")
        self.gridLayout_5.addWidget(self.label_20, 1, 6, 1, 1, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setStyleSheet("background-color: rgb(46, 52, 54);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_5.addWidget(self.line, 7, 1, 1, 6)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.up = QtWidgets.QPushButton(self.centralwidget)
        self.up.setObjectName("up")
        self.gridLayout_2.addWidget(self.up, 1, 2, 1, 1)
        self.stop = QtWidgets.QPushButton(self.centralwidget)
        self.stop.setObjectName("stop")
        self.gridLayout_2.addWidget(self.stop, 2, 2, 1, 1)
        self.right = QtWidgets.QPushButton(self.centralwidget)
        self.right.setObjectName("right")
        self.gridLayout_2.addWidget(self.right, 2, 3, 1, 1)
        self.down = QtWidgets.QPushButton(self.centralwidget)
        self.down.setObjectName("down")
        self.gridLayout_2.addWidget(self.down, 3, 2, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setStyleSheet("background-color: rgb(46, 52, 54);")
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_2.addWidget(self.line_3, 0, 0, 4, 1)
        self.left = QtWidgets.QPushButton(self.centralwidget)
        self.left.setObjectName("left")
        self.gridLayout_2.addWidget(self.left, 2, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 0, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 8, 3, 1, 4)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_11.addWidget(self.label_19)
        self.y_aim = QtWidgets.QLineEdit(self.centralwidget)
        self.y_aim.setObjectName("y_aim")
        self.horizontalLayout_11.addWidget(self.y_aim)
        self.gridLayout_4.addLayout(self.horizontalLayout_11, 2, 0, 1, 1)
        self.send_loc = QtWidgets.QPushButton(self.centralwidget)
        self.send_loc.setObjectName("send_loc")
        self.gridLayout_4.addWidget(self.send_loc, 3, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_10.addWidget(self.label_18)
        self.x_aim = QtWidgets.QLineEdit(self.centralwidget)
        self.x_aim.setObjectName("x_aim")
        self.horizontalLayout_10.addWidget(self.x_aim)
        self.gridLayout_4.addLayout(self.horizontalLayout_10, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 8, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.iptext = QtWidgets.QLineEdit(self.centralwidget)
        self.iptext.setObjectName("iptext")
        self.horizontalLayout.addWidget(self.iptext)
        self.start_server = QtWidgets.QPushButton(self.centralwidget)
        self.start_server.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.start_server.setObjectName("start_server")
        self.horizontalLayout.addWidget(self.start_server)
        self.gridLayout_5.addLayout(self.horizontalLayout, 9, 1, 1, 6)
        self.tabWidget_4 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_4.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.tab_5)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_8 = QtWidgets.QLabel(self.tab_5)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.linea_text = QtWidgets.QLineEdit(self.tab_5)
        self.linea_text.setObjectName("linea_text")
        self.horizontalLayout_3.addWidget(self.linea_text)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_9 = QtWidgets.QLabel(self.tab_5)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.angual_text = QtWidgets.QLineEdit(self.tab_5)
        self.angual_text.setObjectName("angual_text")
        self.horizontalLayout_4.addWidget(self.angual_text)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.label_15 = QtWidgets.QLabel(self.tab_5)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_3.addWidget(self.label_15)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_10 = QtWidgets.QLabel(self.tab_5)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10)
        self.x_text = QtWidgets.QLineEdit(self.tab_5)
        self.x_text.setObjectName("x_text")
        self.horizontalLayout_5.addWidget(self.x_text)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_11 = QtWidgets.QLabel(self.tab_5)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_6.addWidget(self.label_11)
        self.y_text = QtWidgets.QLineEdit(self.tab_5)
        self.y_text.setObjectName("y_text")
        self.horizontalLayout_6.addWidget(self.y_text)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_12 = QtWidgets.QLabel(self.tab_5)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_7.addWidget(self.label_12)
        self.z_text = QtWidgets.QLineEdit(self.tab_5)
        self.z_text.setObjectName("z_text")
        self.horizontalLayout_7.addWidget(self.z_text)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_13 = QtWidgets.QLabel(self.tab_5)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_8.addWidget(self.label_13)
        self.w_text = QtWidgets.QLineEdit(self.tab_5)
        self.w_text.setObjectName("w_text")
        self.horizontalLayout_8.addWidget(self.w_text)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.label_16 = QtWidgets.QLabel(self.tab_5)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_3.addWidget(self.label_16)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_14 = QtWidgets.QLabel(self.tab_5)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_9.addWidget(self.label_14)
        self.yaw_text = QtWidgets.QLineEdit(self.tab_5)
        self.yaw_text.setObjectName("yaw_text")
        self.horizontalLayout_9.addWidget(self.yaw_text)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.tabWidget_4.addTab(self.tab_5, "")
        self.gridLayout_5.addWidget(self.tabWidget_4, 3, 1, 3, 2)
        self.video_accpect = QtWidgets.QCheckBox(self.centralwidget)
        self.video_accpect.setObjectName("video_accpect")
        self.gridLayout_5.addWidget(self.video_accpect, 6, 5, 1, 2, QtCore.Qt.AlignRight)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setStyleSheet("background-color: rgb(46, 52, 54);")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_5.addWidget(self.line_2, 2, 0, 1, 7)
        self.tabWidget_3 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_3.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.commuaction = QtWidgets.QTextEdit(self.tab_3)
        self.commuaction.setObjectName("commuaction")
        self.verticalLayout_2.addWidget(self.commuaction)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.text = QtWidgets.QTextEdit(self.tab_3)
        self.text.setObjectName("text")
        self.verticalLayout.addWidget(self.text)
        self.sendbtn = QtWidgets.QPushButton(self.tab_3)
        self.sendbtn.setObjectName("sendbtn")
        self.verticalLayout.addWidget(self.sendbtn)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.tabWidget_3.addTab(self.tab_3, "")
        self.gridLayout_5.addWidget(self.tabWidget_3, 3, 0, 8, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setStyleSheet("font: 75 33pt \"Ubuntu Mono\";")
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 1, 0, 1, 6, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.video.setText(_translate("MainWindow", "         NO IMAGE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "视频跟踪"))
        self.speed_accpect.setToolTip(_translate("MainWindow", "<html><head/><body><p>点击订阅小车参数</p></body></html>"))
        self.speed_accpect.setText(_translate("MainWindow", "点击订阅"))
        self.label_3.setText(_translate("MainWindow", "服务器端口号："))
        self.disconnect.setText(_translate("MainWindow", "断开连接"))
        self.label_20.setText(_translate("MainWindow", "icon"))
        self.up.setText(_translate("MainWindow", "前进"))
        self.stop.setText(_translate("MainWindow", "停止"))
        self.right.setText(_translate("MainWindow", "右转"))
        self.down.setText(_translate("MainWindow", "后退"))
        self.left.setText(_translate("MainWindow", "左转"))
        self.label_17.setText(_translate("MainWindow", "速度控制："))
        self.label_5.setText(_translate("MainWindow", "设置目标点："))
        self.label_19.setText(_translate("MainWindow", "  y："))
        self.send_loc.setText(_translate("MainWindow", "位置发送"))
        self.label_18.setText(_translate("MainWindow", "  x："))
        self.label.setText(_translate("MainWindow", "服务器ip地址："))
        self.start_server.setText(_translate("MainWindow", "连接服务器"))
        self.label_7.setText(_translate("MainWindow", "小车实时参数："))
        self.label_8.setText(_translate("MainWindow", "线速度"))
        self.label_9.setText(_translate("MainWindow", "角速度"))
        self.label_15.setText(_translate("MainWindow", "里程计："))
        self.label_10.setText(_translate("MainWindow", "x"))
        self.label_11.setText(_translate("MainWindow", "y"))
        self.label_12.setText(_translate("MainWindow", "z"))
        self.label_13.setText(_translate("MainWindow", "w"))
        self.label_16.setText(_translate("MainWindow", "IMU："))
        self.label_14.setText(_translate("MainWindow", "yaw"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_5), _translate("MainWindow", "小车参数通信"))
        self.video_accpect.setToolTip(_translate("MainWindow", "<html><head/><body><p>点击订阅摄像头数据</p></body></html>"))
        self.video_accpect.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.video_accpect.setText(_translate("MainWindow", "点击订阅"))
        self.label_2.setText(_translate("MainWindow", "通信显示框："))
        self.label_4.setText(_translate("MainWindow", "发送数据："))
        self.sendbtn.setText(_translate("MainWindow", "数据发送"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_3), _translate("MainWindow", "文本通信"))
        self.label_6.setText(_translate("MainWindow", "    智 能 车 中 央 调 度 系 统 v 1.0"))
